#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("astroud-palindrome");
let palindromes = "";

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    palindromes += line.concat("\n");
  }
});

fs.writeFileSync("palindromes.txt", palindromes);